sudo: required

scala:
  - "2.11.8"

os: linux
dist: trusty
jdk: oraclejdk8
language: scala

env:
  matrix:
    - SCALANATIVE_GC=boehm
    - SCALANATIVE_GC=immix

before_install:
  - sudo apt-get update
  # Remove pre-bundled libunwind
  - sudo find /usr -name "*libunwind*" -delete
  # Use pre-bundled clang
  - export PATH=/usr/local/clang-5.0.0/bin:$PATH
  - export CXX=clang++
  # Install Boehm GC and libunwind
  - sudo apt-get install libgc-dev libunwind8-dev
  # Build and install re2 from source
  - git clone https://code.googlesource.com/re2
  - pushd re2
  - git checkout 2017-03-01
  - make -j4 test
  - sudo make install prefix=/usr
  - make testinstall prefix=/usr
  - popd

script:
  - sbt ";clean;rootJVM/test;rootNative/test"

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -rf $HOME/.ivy2/{cache,local}/org.scala-native/

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
